// <auto-generated />
using HMACServerApp.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace HMACServerApp.Migrations
{
    [DbContext(typeof(HMACDbContext))]
    partial class HMACDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("HMACServerApp.Models.ClientSecret", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClientId")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("SecretKey")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("Id");

                    b.ToTable("ClientSecrets");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ClientId = "WebAppClient",
                            SecretKey = "a1b2c3d4e5f6g7h8i9j0"
                        },
                        new
                        {
                            Id = 2,
                            ClientId = "MobileAppClient",
                            SecretKey = "z9y8x7w6v5u4t3s2r1q0"
                        },
                        new
                        {
                            Id = 3,
                            ClientId = "DesktopClient",
                            SecretKey = "m1n2b3v4c5x6z7i8k9j0"
                        });
                });

            modelBuilder.Entity("HMACServerApp.Models.Employee", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Position")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<decimal>("Salary")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.ToTable("Employees");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Alice Johnson",
                            Position = "Software Engineer",
                            Salary = 75000m
                        },
                        new
                        {
                            Id = 2,
                            Name = "Bob Smith",
                            Position = "Project Manager",
                            Salary = 85000m
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
